language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.3
  - 2.2.6
  - 2.1.9
addons:
  apt:
    packages:
    - libicu-dev
branches:
  only:
    - devel
    - /^v1\..*$/
after_success:
  - bundle exec codeclimate-test-reporter
