language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
addons:
  apt:
    packages:
    - libicu-dev
branches:
  only:
    - devel
    - /^v1\..*$/
after_success:
  - bundle exec codeclimate-test-reporter
