language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
addons:
  apt:
    packages:
    - libicu-dev
branches:
  only:
    - devel
    - /^v1\..*$/
after_success:
  - bundle exec codeclimate-test-reporter
